ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "passportMint" TEXT;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "passportMintedAt" TIMESTAMP(3);
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "passportTxHash" TEXT;
